In [26]:
import numpy as np 

In [27]:
s=[0., 0, 0, 0, 0, 0, 0, 0, 0, 0]
s

[0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [30]:
np.array(s)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
array=np.ones(10)
array


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
array=np.ones(10)*5
array


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [39]:
array=np.arange(10,51,1)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [40]:
array=np.arange(0, 9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
array=np.identity(3)
array


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
array = np.random.normal(0,1,1)
array

array([0.92929694])

In [46]:
array=np.random.normal(0,1,25)
array

array([ 1.83799658,  0.94015118, -1.83528469, -1.27505299,  0.09936419,
       -2.36925713,  0.89649533, -1.50046323,  0.28297234, -1.23239512,
        0.18428336,  1.18472957, -1.09504797, -0.89446454, -0.18834912,
       -0.73496924,  0.2431759 , -0.07688185,  1.45974892,  0.85283878,
       -0.82779587, -1.1018186 ,  1.32446207, -0.42698744,  1.35474649])

In [48]:
array=np.arange(0.01,1.01,0.01)
array

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [49]:
array= np.linspace(0,1,20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [58]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
mat[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [65]:
mat[3,4]

20

In [66]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [67]:
mat.sum()

325

In [73]:
mat = np.arange(1,26).reshape(5,5)
mat[4: ]

array([[21, 22, 23, 24, 25]])

In [74]:
mat[3: ]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
mat.sum()

325

In [76]:
mat.std()

7.211102550927978

In [79]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [97]:
np.random.seed(seed=0)
array=np.random.randint(10,size=(5,3))
array

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [98]:
s=[0., 0, 0, 0, 0, 0, 0, 0, 0, 0]
array=np.array(s)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
array=np.arange(10,51,2)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##pandas task:



import pandas as pd

In [1]:
import pandas as pd 

In [2]:
hotels = pd.read_csv("hotel_booking_data.csv")
hotels.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  customer_type  \
0                        0                     0       2  ...      Transient   
1                        0                     0       2  ...      Transient   
2                        0                     1       1  ...      Transient   
3                        0                     1       1  ...      Transient   
4                        0                     2       2  ...      Transient   

    adr required_car_parking_spaces total_of_special_requests  \
0   0.0                           0                         0   
1   0.0                           0                         0   
2  75.0                           0                         0   
3  75.0                           0                         0   
4  98.0                           0                         1   

  reservation_status reservation_status_date            name  \
0          Check-Out              2015-07-01   Ernest Barnes   
1          Check-Out              2015-07-01    Andrea Baker   
2          Check-Out              2015-07-02  Rebecca Parker   
3          Check-Out              2015-07-02    Laura Murray   
4          Check-Out              2015-07-03     Linda Hines   

                         email  phone-number       credit_card  
0  Ernest.Barnes31@outlook.com  669-792-1661  ************4322  
1       Andrea_Baker94@aol.com  858-637-6955  ************9157  
2   Rebecca_Parker@comcast.net  652-885-2745  ************3734  
3            Laura_M@gmail.com  364-656-8427  ************5677  
4           LHines@verizon.com  713-226-5883  ************5498  

[5 rows x 36 columns]

In [5]:
rows = len(hotels)
rows

119390

In [8]:
hotels.isnull()

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
0       False        False      False              False               False   
1       False        False      False              False               False   
2       False        False      False              False               False   
3       False        False      False              False               False   
4       False        False      False              False               False   
...       ...          ...        ...                ...                 ...   
119385  False        False      False              False               False   
119386  False        False      False              False               False   
119387  False        False      False              False               False   
119388  False        False      False              False               False   
119389  False        False      False              False               False   

        arrival_date_week_number  arrival_date_day_of_month  \
0                          False                      False   
1                          False                      False   
2                          False                      False   
3                          False                      False   
4                          False                      False   
...                          ...                        ...   
119385                     False                      False   
119386                     False                      False   
119387                     False                      False   
119388                     False                      False   
119389                     False                      False   

        stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                         False                 False   False  ...   
1                         False                 False   False  ...   
2                         False                 False   False  ...   
3                         False                 False   False  ...   
4                         False                 False   False  ...   
...                         ...                   ...     ...  ...   
119385                    False                 False   False  ...   
119386                    False                 False   False  ...   
119387                    False                 False   False  ...   
119388                    False                 False   False  ...   
119389                    False                 False   False  ...   

        customer_type    adr  required_car_parking_spaces  \
0               False  False                        False   
1               False  False                        False   
2               False  False                        False   
3               False  False                        False   
4               False  False                        False   
...               ...    ...                          ...   
119385          False  False                        False   
119386          False  False                        False   
119387          False  False                        False   
119388          False  False                        False   
119389          False  False                        False   

        total_of_special_requests  reservation_status  \
0                           False               False   
1                           False               False   
2                           False               False   
3                           False               False   
4                           False               False   
...                           ...                 ...   
119385                      False               False   
119386                      False               False   
119387                      False               False   
119388                      False               False   
119389                      False               False   

        reservation_status_date

In [12]:
hotels.isna()

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
0       False        False      False              False               False   
1       False        False      False              False               False   
2       False        False      False              False               False   
3       False        False      False              False               False   
4       False        False      False              False               False   
...       ...          ...        ...                ...                 ...   
119385  False        False      False              False               False   
119386  False        False      False              False               False   
119387  False        False      False              False               False   
119388  False        False      False              False               False   
119389  False        False      False              False               False   

        arrival_date_week_number  arrival_date_day_of_month  \
0                          False                      False   
1                          False                      False   
2                          False                      False   
3                          False                      False   
4                          False                      False   
...                          ...                        ...   
119385                     False                      False   
119386                     False                      False   
119387                     False                      False   
119388                     False                      False   
119389                     False                      False   

        stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                         False                 False   False  ...   
1                         False                 False   False  ...   
2                         False                 False   False  ...   
3                         False                 False   False  ...   
4                         False                 False   False  ...   
...                         ...                   ...     ...  ...   
119385                    False                 False   False  ...   
119386                    False                 False   False  ...   
119387                    False                 False   False  ...   
119388                    False                 False   False  ...   
119389                    False                 False   False  ...   

        customer_type    adr  required_car_parking_spaces  \
0               False  False                        False   
1               False  False                        False   
2               False  False                        False   
3               False  False                        False   
4               False  False                        False   
...               ...    ...                          ...   
119385          False  False                        False   
119386          False  False                        False   
119387          False  False                        False   
119388          False  False                        False   
119389          False  False                        False   

        total_of_special_requests  reservation_status  \
0                           False               False   
1                           False               False   
2                           False               False   
3                           False               False   
4                           False               False   
...                           ...                 ...   
119385                      False               False   
119386                      False               False   
119387                      False               False   
119388                      False               False   
119389                      False               False   

        reservation_status_date

In [14]:
hotels.isnull().values.any()

True

In [15]:
hotels.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [39]:
hotels.isnull().any()

hotel                             False
is_canceled                       False
lead_time                         False
arrival_date_year                 False
arrival_date_month                False
arrival_date_week_number          False
arrival_date_day_of_month         False
stays_in_weekend_nights           False
stays_in_week_nights              False
adults                            False
children                           True
babies                            False
meal                              False
country                            True
market_segment                    False
distribution_channel              False
is_repeated_guest                 False
previous_cancellations            False
previous_bookings_not_canceled    False
reserved_room_type                False
assigned_room_type                False
booking_changes                   False
deposit_type                      False
agent                              True
company                            True


In [168]:
import numpy as np
def convert(day, month, year):
    return f"{day}-{month}-{year}"
hotels['date'] = np.vectorize(convert)(hotels['arrival_date_day_of_month'],
                                                          hotels['arrival_date_month'],
                                                          hotels['arrival_date_year'])
hotels['date'] = pd.to_datetime(hotels['date'])
hotels['date'].dt.day_name().value_counts()


Friday       19631
Thursday     19254
Monday       18171
Saturday     18055
Wednesday    16139
Sunday       14141
Tuesday      13999
Name: date, dtype: int64

In [37]:
df2=hotels['company']
df2

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
119385   NaN
119386   NaN
119387   NaN
119388   NaN
119389   NaN
Name: company, Length: 119390, dtype: float64

In [44]:
hotels.nlargest(n=5, columns=[Index])

NameError: name 'Index' is not defined

In [45]:
from pandas.api.types import is_numeric_dtype

dfs = []
for col in hotels.columns:
    top_values = []
    if is_numeric_dtype(hotels[col]):
        top_values = hotels[col].nlargest(n=7)
        dfs.append(pd.DataFrame({col: top_values}).reset_index(drop=True))
pd.concat(dfs, axis=1)

is_canceled  lead_time  arrival_date_year  arrival_date_week_number  \
0            1        737               2017                        53   
1            1        709               2017                        53   
2            1        629               2017                        53   
3            1        629               2017                        53   
4            1        629               2017                        53   
5            1        629               2017                        53   
6            1        629               2017                        53   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                         31                       19                    50   
1                         31                       18                    42   
2                         31                       16                    41   
3                         31                       16                    40   
4                         31                       16                    40   
5                         31                       14                    35   
6                         31                       14                    34   

   adults  children  babies  is_repeated_guest  previous_cancellations  \
0      55      10.0      10                  1                      26   
1      50       3.0       9                  1                      26   
2      40       3.0       2                  1                      26   
3      27       3.0       2                  1                      26   
4      27       3.0       2                  1                      26   
5      26       3.0       2                  1                      26   
6      26       3.0       2                  1                      26   

   previous_bookings_not_canceled  booking_changes  agent  company  \
0                              72               21  535.0    543.0   
1                              71               20  535.0    543.0   
2                              70               18  535.0    541.0   
3                              69               17  531.0    539.0   
4                              68               17  531.0    539.0   
5                              67               16  531.0    534.0   
6                              66               16  531.0    534.0   

   days_in_waiting_list      adr  required_car_parking_spaces  \
0                   391  5400.00                            8   
1                   391   510.00                            8   
2                   391   508.00                            3   
3                   391   451.50                            3   
4                   391   450.00                            3   
5                   391   437.00                            2   
6                   391   426.25                            2   

   total_of_special_requests  
0                          5  
1                          5  
2                          5  
3                          5  
4                          5  
5                          5  
6                          5

In [67]:
hotels['lead_time'].nlargest(n=5)

1        737
4182     709
65231    629
65235    629
65237    629
Name: lead_time, dtype: int64

In [69]:
hotels.shape[0]


119390

In [70]:
rows = len(hotels)
rows

119390

In [72]:
print('Yes, missing data, company column missing: 112593 rows.')

Yes, missing data, company column missing: 112593 rows.


In [77]:
s=round(hotels['adr'].mean(), 2)
s

101.83

In [78]:
s=round(hotels['adr'].mean(), 2)
s

101.83

In [79]:
hotels['total_nights'] = hotels['stays_in_weekend_nights'] + hotels['stays_in_week_nights']
hotels['total_nights']
s=round(hotels['total_nights'].mean(), 2)
s

3.43

In [80]:
hotels['total_stay_cost'] = hotels['total_nights'] * hotels['adr']
s=round(hotels['total_stay_cost'].mean(), 2)
s

357.85

In [81]:
hotels['total_of_special_requests'].head()

0    0
1    0
2    0
3    0
4    1
Name: total_of_special_requests, dtype: int64

In [152]:
s=hotels[hotels['total_of_special_requests'] == 5][['name', 'email']]
s

name                          email
7860             Amanda Harper           Amanda.H66@yahoo.com
11125            Laura Sanders      Sanders_Laura@hotmail.com
14596              Tommy Ortiz            Tommy_O@hotmail.com
14921           Gilbert Miller         Miller.Gilbert@aol.com
14922           Timothy Torres         TTorres@protonmail.com
24630          Jennifer Weaver             Jennifer_W@aol.com
27288           Crystal Horton             Crystal.H@mail.com
27477           Brittney Burke       Burke_Brittney16@att.com
29906          Cynthia Cabrera    Cabrera.Cynthia@xfinity.com
29949              Sarah Floyd              Sarah_F@gmail.com
32267           Michelle Villa         Michelle.Villa@aol.com
39027           Nichole Hebert       Hebert.Nichole@gmail.com
39129         Lindsey Mckenzie       Lindsey.Mckenzie@att.com
39525           Ashley Edwards       Edwards.Ashley@yahoo.com
70114       Christopher Torres   Torres.Christopher@gmail.com
78819   Mrs. Tara Sullivan DVM           Mrs..DVM@xfinity.com
78820           Michaela Brown          MichaelaBrown@att.com
78822        Kurt Maldonado MD              KMD15@xfinity.com
97072         Jason Richardson               Jason.R@zoho.com
97099             Terri Hurley            THurley@xfinity.com
97261        Mrs. Caitlin Webb             Mrs._W@comcast.net
98410             Holly Arroyo          Arroyo_Holly@mail.com
98674          Denise Campbell             Denise_C@gmail.com
99887            Michael Smith            Michael.S42@aol.com
99888       Dr. Trevor Sellers                  Dr._S@aol.com
101569            Kayla Murphy         Kayla.Murphy@yahoo.com
102061         Taylor Martinez    Taylor.Martinez@hotmail.com
109511          Charles Wilson       Charles_Wilson@yahoo.com
109590           Tyler Allison         Tyler.A@protonmail.com
110082          Matthew Bailey         Matthew_Bailey@aol.com
110083       Charlotte Acevedo        Charlotte_A@verizon.com
111909         Darrell Brennan  Brennan_Darrell51@hotmail.com
111911          Melinda Jensen         MelindaJensen@zoho.com
113915            Terry Arnold          Arnold.Terry@zoho.com
114770             Mary Nguyen     Nguyen.Mary@protonmail.com
114909          Lindsay Cuevas      Lindsay.Cuevas40@mail.com
116455       Cynthia Hernandez   CynthiaHernandez@xfinity.com
116457          Angela Hawkins             Angela_H@gmail.com
118817              Sue Lawson            Sue.L52@comcast.net
119161         Alyssa Richards        Alyssa_Richards@aol.com

In [160]:
hotels['arrival_full_date'].dt.weekday

0         2
1         2
2         2
3         2
4         2
         ..
119385    2
119386    3
119387    3
119388    3
119389    1
Name: arrival_full_date, Length: 119390, dtype: int64

In [165]:

hotels['arrival_full_date'] = pd.to_datetime(hotels['arrival_full_date'], dayfirst=True)
hotels['arrival_full_date'].dt.weekday

weekday_dict = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday', 
    5: 'Saturday',
    6: 'Sunday'
}
hotels['date'].dt.day_name().value_counts()

KeyError: 'date'

In [161]:
weekday_dict = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday', 
    5: 'Saturday',
    6: 'Sunday'
}
hotels.groupby('arrival_day_of_week').count()['hotel']

arrival_day_of_week
Friday       18171
Monday       16139
Saturday     19254
Sunday       18055
Thursday     13999
Tuesday      14141
Wednesday    19631
Name: hotel, dtype: int64

In [164]:
hotels.groupby('arrival_day_of_week').count()['hotel']

arrival_day_of_week
Friday       18171
Monday       16139
Saturday     19254
Sunday       18055
Thursday     13999
Tuesday      14141
Wednesday    19631
Name: hotel, dtype: int64

In [85]:

total_repeated_stays = hotels['is_repeated_guest'].value_counts()[1]
total_non_repeated_stays = hotels['is_repeated_guest'].value_counts()[0]
round(total_repeated_stays / (total_repeated_stays + total_non_repeated_stays) * 100 , 2)

3.19

In [86]:

hotels['name'].apply(lambda name: name.split(' ')[-1]).value_counts()[:5]

Smith       2503
Johnson     1990
Williams    1618
Jones       1434
Brown       1423
Name: name, dtype: int64

In [87]:
hotels['total_kids'] = hotels['children'] + hotels['babies']
hotels.sort_values(by='total_kids', ascending=False)[['name', 'adults', 'total_kids', 'children', 'babies']][:3]

name  adults  total_kids  children  babies
328      Jamie Ramirez       2        10.0      10.0       0
46619  Nicholas Parker       2        10.0       0.0      10
78656    Marc Robinson       1         9.0       0.0       9

In [126]:
hotels['phone-number'].apply(lambda num: num.split('-')[0]).value_counts()[:3]

799    168
185    167
541    166
Name: phone-number, dtype: int64

In [131]:
weekday_dict = {
    0: 'Friday',
    1: 'Thursday',
    2: 'Monday',
    3: 'Saturday',
    4: 'Wednesday', 
    5: 'Sunday',
    6: 'Tuesday',
}       
hotels.groupby('arrival_day_of_week').count()['hotel']

arrival_day_of_week
Friday       18171
Monday       16139
Saturday     19254
Sunday       18055
Thursday     13999
Tuesday      14141
Wednesday    19631
Name: hotel, dtype: int64

In [132]:
hotels.count()['hotel']

119390

In [136]:
weekday_dict = {
    0: 'Friday',
    1: 'Thursday',
    2: 'Monday',
    3: 'Saturday',
    4: 'Wednesday', 
    5: 'Sunday',
    6: 'Tuesday',
} 
hotels.groupby('arrival_day_of_week').count()['hotel']

arrival_day_of_week
Friday       18171
Monday       16139
Saturday     19254
Sunday       18055
Thursday     13999
Tuesday      14141
Wednesday    19631
Name: hotel, dtype: int64

In [138]:
hotels['arrival_day_of_week'] = hotels['arrival_full_date'].dt.weekday.map(weekday_dict)
hotels.groupby('arrival_day_of_week').count()['hotel']

arrival_day_of_week
Friday       18171
Monday       16139
Saturday     19254
Sunday       18055
Thursday     13999
Tuesday      14141
Wednesday    19631
Name: hotel, dtype: int64

In [139]:
hotels.head(2)


hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                        0                     0       2  ...   
1                        0                     0       2  ...   

   reservation_status_date           name                        email  \
0               2015-07-01  Ernest Barnes  Ernest.Barnes31@outlook.com   
1               2015-07-01   Andrea Baker       Andrea_Baker94@aol.com   

   phone-number       credit_card total_nights  total_stay_cost  total_kids  \
0  669-792-1661  ************4322            0              0.0         0.0   
1  858-637-6955  ************9157            0              0.0         0.0   

   arrival_full_date arrival_day_of_week  
0         2015-07-01              Monday  
1         2015-07-01              Monday  

[2 rows x 41 columns]

In [150]:
hotels['arrival_full_date'] = pd.to_datetime(hotels['arrival_full_date'], dayfirst=True)
hotels.head(2)

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                        0                     0       2  ...   
1                        0                     0       2  ...   

   reservation_status_date           name                        email  \
0               2015-07-01  Ernest Barnes  Ernest.Barnes31@outlook.com   
1               2015-07-01   Andrea Baker       Andrea_Baker94@aol.com   

   phone-number       credit_card total_nights  total_stay_cost  total_kids  \
0  669-792-1661  ************4322            0              0.0         0.0   
1  858-637-6955  ************9157            0              0.0         0.0   

   arrival_full_date arrival_day_of_week  
0         2015-07-01              Monday  
1         2015-07-01              Monday  

[2 rows x 41 columns]

In [151]:
hotels['arrival_full_date'].dt.weekday

0         2
1         2
2         2
3         2
4         2
         ..
119385    2
119386    3
119387    3
119388    3
119389    1
Name: arrival_full_date, Length: 119390, dtype: int64

In [ ]:
)

In [89]:
len(hotels[(hotels['arrival_date_day_of_month'] >= 1) & (hotels['arrival_date_day_of_month'] <= 15)])


58152

In [98]:
hotels['arrival_date_day_of_month'].apply(lambda day: day in range(1, 16))

0          True
1          True
2          True
3          True
4          True
          ...  
119385    False
119386    False
119387    False
119388    False
119389    False
Name: arrival_date_day_of_month, Length: 119390, dtype: bool

In [105]:
hotels['arrival_full_date'] = hotels[['arrival_date_day_of_month', 'arrival_date_month', 'arrival_date_year']].apply(lambda df: make_date(
                                                                                                                            df['arrival_date_day_of_month'], 
                                                                                                                            df['arrival_date_month'],
                                                                                                                            df['arrival_date_year']), axis=1)
# convert to datetime
hotels['arrival_full_date'] = pd.to_datetime(hotels['arrival_full_date'], dayfirst=True)
hotels.head(2)
hotels['arrival_full_date'].dt.weekday
weekday_dict = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday', 
    5: 'Saturday',
    6: 'Sunday'
}


In [125]:
weekday_dict = {
    0: 'Friday',
    1: 'Monday',
    2: 'Saturday',
    3: 'Sunday',
    4: 'Thursday', 
    5: 'Tuesday',
    6: 'Wendesday',
} 

hotels.groupby('arrival_day_of_week').count()['hotel']

arrival_day_of_week
Friday       19631
Monday       18171
Saturday     18055
Sunday       14141
Thursday     19254
Tuesday      13999
Wednesday    16139
Name: hotel, dtype: int64

In [76]:
s=round(hotels['total_nights'].mean(), 2)
s

KeyError: 'total_nights'

In [51]:
hotels.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card'],
      dtype='object')

In [42]:
d=hotels.columns
d

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card'],
      dtype='object')

In [64]:
l=hotels.index
l

RangeIndex(start=0, stop=119390, step=1)

In [ ]:
s